-- MIGRATION: SKILLS MANAGEMENT SYSTEM

-- 1. Create Categories Table
create table if not exists public.skill_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text, -- Optional: Material Icon name
  "displayOrder" int default 0
);

-- 2. Create Skills Table
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  "categoryId" bigint references public.skill_categories(id) on delete cascade not null,
  icon text -- Optional: SVG path or URL or Icon name
);

-- 3. Create Project Skills Junction Table
create table if not exists public.project_skills (
  "projectId" bigint references public.projects(id) on delete cascade not null,
  "skillId" bigint references public.skills(id) on delete cascade not null,
  primary key ("projectId", "skillId")
);

-- 4. Enable RLS
alter table public.skill_categories enable row level security;
alter table public.skills enable row level security;
alter table public.project_skills enable row level security;

-- 5. Policies
-- Categories: Public Read, Auth Write
create policy "Public Read Categories" on public.skill_categories for select using (true);
create policy "Auth Write Categories" on public.skill_categories for insert with check (auth.role() = 'authenticated');
create policy "Auth Update Categories" on public.skill_categories for update using (auth.role() = 'authenticated');
create policy "Auth Delete Categories" on public.skill_categories for delete using (auth.role() = 'authenticated');

-- Skills: Public Read, Auth Write
create policy "Public Read Skills" on public.skills for select using (true);
create policy "Auth Write Skills" on public.skills for insert with check (auth.role() = 'authenticated');
create policy "Auth Update Skills" on public.skills for update using (auth.role() = 'authenticated');
create policy "Auth Delete Skills" on public.skills for delete using (auth.role() = 'authenticated');

-- Project Skills: Public Read, Auth Write
create policy "Public Read Project Skills" on public.project_skills for select using (true);
create policy "Auth Write Project Skills" on public.project_skills for insert with check (auth.role() = 'authenticated');
create policy "Auth Update Project Skills" on public.project_skills for update using (auth.role() = 'authenticated');
create policy "Auth Delete Project Skills" on public.project_skills for delete using (auth.role() = 'authenticated');

-- 6. Seed Initial Categories
insert into public.skill_categories (name, icon, "displayOrder") values
('Lenguajes', 'code', 1),
('Frameworks', 'layers', 2),
('Librerías', 'local_library', 3),
('APIs', 'api', 4),
('Plataformas', 'dns', 5),
('Herramientas', 'build', 6)
on conflict (name) do nothing;
