-- 1. Enable RLS on all tables we create
-- (Recommended for security, though we are allowing puiblic access for now based on your current auth setup)

-- PROJECTS TABLE
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  frameworks text[],
  apis text[],
  libraries text[],
  platforms text[],
  languages text[],
  "markupStyles" text[],
  company text,
  "companyUrl" text,
  role text,
  images text[],
  "liveUrl" text,
  "repoUrl" text,
  featured boolean default false,
  "currentImageIndex" int default 0,
  progress int default 0
);
alter table public.projects enable row level security;
create policy "Enable read access for all users" on public.projects for select using (true);
create policy "Enable insert for all users" on public.projects for insert with check (true);
create policy "Enable update for all users" on public.projects for update using (true);
create policy "Enable delete for all users" on public.projects for delete using (true);

-- SOCIAL NETWORKS TABLE
create table if not exists public.social_networks (
  id bigint generated by default as identity primary key,
  name text not null,
  nick text,
  "iconPath" text,
  url text
);
alter table public.social_networks enable row level security;
create policy "Enable read access for all users" on public.social_networks for select using (true);
create policy "Enable modification for all users" on public.social_networks for all using (true);

-- CONTACT METHODS TABLE
create table if not exists public.contact_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  nick text,
  "iconPath" text,
  url text
);
alter table public.contact_methods enable row level security;
create policy "Enable read access for all users" on public.contact_methods for select using (true);
create policy "Enable modification for all users" on public.contact_methods for all using (true);

-- STORAGE BUCKET
insert into storage.buckets (id, name, public) 
values ('portfolio-assets', 'portfolio-assets', true)
on conflict (id) do nothing;

create policy "Public Access" on storage.objects for select using ( bucket_id = 'portfolio-assets' );
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'portfolio-assets' );
create policy "Public Update" on storage.objects for update using ( bucket_id = 'portfolio-assets' );
